# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amazingly Abstract
email: federiconafria@gmail.com
description: |
  A Software&nbsp;Engineering Blog by&nbsp;<a href=/about>Federico&nbsp;Nafria</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amazinglyabstract.it" # the base hostname & protocol for your site
github_username:  driv
twitter_username: federiconafria
linkedin_username:  federiconafria

# Build settings
markdown: kramdown

